import clientBasedProjects from './clientbasedprojects';

const personalProjects = {
  developerTools: [
    {
      name: 'Readme Generator Pro',
      description: 'A professional README generator built with React and TypeScript that helps developers create beautiful, comprehensive README files for their GitHub projects.',
      imageUrl: ['https://res.cloudinary.com/db3m7jneg/image/upload/v1739186314/Macbook-Air-readme-generator-pro.vercel.app_ivieui.png'],
      liveUrl: 'https://readme-generator-pro.vercel.app/',
      githubUrl: 'https://github.com/Fredrickmureti/Readme_Generator_Pro',
      tags: ['JavaScript', 'TypeScript', 'TailwindCSS', 'React'],
      isPrivate: false,
    },
    {
      name: 'Dev Utils Hub',
      description: 'A comprehensive collection of developer utilities designed to streamline your workflow. This application provides various tools that developers frequently need, all in one place.',
      imageUrl: ['https://res.cloudinary.com/db3m7jneg/image/upload/v1739184931/Macbook-Air-dev-utils-hub.vercel.app_wux06h.png'],
      liveUrl: 'https://dev-utils-hub.vercel.app/',
      githubUrl: 'https://github.com/Fredrickmureti/Dev_Utils_Hub',
      tags: ['React', 'Tailwind CSS', 'TypeScript'],
      isPrivate: false,
    },
    {
      name: 'Type Script Interface Generator',
      description: 'This platform enables developers to quickly generate TypeScript interfaces from JSON data by simply uploading a file or pasting the content, eliminating manual coding and saving time.',
      imageUrl: ['https://res.cloudinary.com/db3m7jneg/image/upload/v1741087788/Macbook-Air-type-script-interface-generator.vercel.app_kiygs0.png'],
      liveUrl: 'https://type-script-interface-generator.vercel.app/',
      githubUrl: 'https://github.com/TypeScript Interface Generator',
      tags: ['JavaScript', 'React', 'Tailwind CSS', 'Typescript'],
      isPrivate: false,
    },
    {
      name: 'Gradient Generator Pro',
      description: 'A powerful and beautiful gradient generator built with React and TypeScript that helps developers create stunning gradients visually and get the code in multiple formats.',
      imageUrl: ['https://res.cloudinary.com/db3m7jneg/image/upload/v1739233854/Macbook-Air-gradient-generator-pro.vercel.app_oosrin.png'],
      liveUrl: 'https://gradient-generator-pro.vercel.app/',
      githubUrl: 'https://github.com/Fredrickmureti/Gradient_Generator_Pro',
      tags: ['JavaScript', 'React', 'Tailwind CSS', 'Typescript'],
      isPrivate: false,
    },
    {
      name: 'Markdown Previewer',
      description: 'A simple Markdown Previewer built with React that allows users to write and preview Markdown content in real-time. The application includes features for toggling between full-screen modes for the editor and the previewer.',
      imageUrl: ['https://res.cloudinary.com/db3m7jneg/image/upload/v1739223871/Macbook-Air-markdown-previewer-roan-seven.vercel.app_tmqug7.png'],
      liveUrl: 'https://markdown-previewer-roan-seven.vercel.app/',
      githubUrl: 'https://github.com/Fredrickmureti/Markdown-previewer',
      tags: ['JavaScript', 'React', 'CSS'],
      isPrivate: false,
    },
  ],
  clientBasedFullStack: clientBasedProjects.map(project => ({
    ...project,
    tags: project.name === 'Mavazi Market' 
      ? ['React', 'Next.js', 'MongoDB', 'Tailwind CSS', 'TypeScript']
      : project.name === 'Cars and Motorbikes Dealership website'
      ? ['JavaScript', 'React', 'CSS', 'Node.js', 'MongoDB', 'Express.js', 'Cloudinary']
      : project.name === 'ISP provider website'
      ? ['React', 'Next.js', 'Tailwind CSS', 'TypeScript']
      : ['React', 'Tailwind CSS', 'Node.js', 'Express.js', 'MongoDB'],
  })),
  fullStackForFun: [
    {
      name: 'TaskMaster Pro',
      description: 'TaskMaster Pro is a powerful task management application designed to enhance productivity. It enables users to set reminders, view real-time calendars, track activities, analyze completion rates, get weekly growth insights, and easily manage tasks.',
      imageUrl: ['https://res.cloudinary.com/db3m7jneg/image/upload/v1739226216/Macbook-Air-task-manager-six-zeta.vercel.app_p9gf5k.png'],
      liveUrl: 'https://task-manager-six-zeta.vercel.app/',
      githubUrl: 'https://github.com/Fredrickmureti/Task_Manager',
      tags: ['JavaScript', 'React', 'CSS', 'Tailwind CSS', 'Typescript'],
      isPrivate: false,
    },
    {
      name: 'Blog Platform',
      description: 'This project is a blog platform where users can write and publish articles. It is built with TypeScript and React, and uses Supabase for storage.',
      imageUrl: ['https://res.cloudinary.com/db3m7jneg/image/upload/v1739228689/Macbook-Air-blog-woad-nine-43.vercel.app_moie3g.png'],
      liveUrl: 'https://blog-woad-nine-43.vercel.app',
      githubUrl: 'https://github.com/Fredrickmureti/blog',
      tags: ['JavaScript', 'React', 'Tailwind CSS', 'Typescript', 'Node.js', 'Express.js', 'MongoDB'],
      isPrivate: false,
    },
    {
      name: 'ERP System',
      description: 'A comprehensive ERP system designed to streamline project management and team collaboration. It enables members to track active projects, monitor individual and team workload, optimize resource utilization, and manage tasks efficiently—all within a centralized platform.',
      imageUrl: ['https://res.cloudinary.com/db3m7jneg/image/upload/v1739190004/Macbook-Air-erp-system-tan.vercel.app_1_zuhcd3.png'],
      liveUrl: 'https://erp-system-tan.vercel.app/',
      githubUrl: 'https://github.com/Fredrickmureti/ERP_SYSTEM-',
      tags: ['JavaScript', 'TypeScript', 'TailwindCSS', 'React', 'Superbase'],
      isPrivate: false,
    },
    {
      name: 'Share Prompts',
      description: 'Share Prompts is a web application that allows users to share and explore creative prompts. This project is built using Next.js, React, and Tailwind CSS, with MongoDB as the database.',
      imageUrl: ['https://res.cloudinary.com/db3m7jneg/image/upload/v1739185594/Macbook-Air-promptshare-platform.vercel.app_zb5nhx.png'],
      liveUrl: 'https://promptshare-platform.vercel.app/',
      githubUrl: 'https://github.com/Fredrickmureti/promptopia-',
      tags: ['React', 'Tailwind CSS', 'TypeScript', 'Next.js', 'MongoDB', 'JavaScript'],
      isPrivate: false,
    },
    {
      name: 'Refine Dashboard',
      description: 'This project is a data-intensive application built using the Refine.dev framework. It provides a robust and flexible platform for managing and displaying data with a modern and intuitive interface.',
      imageUrl: ['https://res.cloudinary.com/db3m7jneg/image/upload/v1739185941/Macbook-Air-refine-dashboard-sigma.vercel.app_mpw0tm.png'],
      liveUrl: 'https://refine-dashboard-sigma.vercel.app/',
      githubUrl: 'https://github.com/Fredrickmureti/REFINE-DASHBOARD',
      tags: ['React', 'Refine', 'TypeScript', 'Tailwind CSS'],
      isPrivate: false,
    },
    {
      name: 'Forex Market Analyzer',
      description: 'This project is a trading bot application that fetches real-time market data, performs analysis, and makes predictions using machine learning models. The application is built using Node.js for the backend, React for the frontend, and Python for the machine learning model.',
      imageUrl: ['https://res.cloudinary.com/db3m7jneg/image/upload/v1739225757/Macbook-Air-market-analysis-platfom-front-end.vercel.app_quiix7.png'],
      liveUrl: 'https://market-analysis-platfom-front-end.vercel.app/',
      githubUrl: 'https://github.com/Fredrickmureti/market-analysis-platfom',
      tags: ['JavaScript', 'React', 'CSS', 'Node.js', 'MongoDB', 'Express.js', 'Python'],
      isPrivate: false,
    },
    {
      name: 'Exercise Tracker App',
      description: 'Exercise Tracker App is a web application that allows users to log their activities, track their exercise routines, and receive notifications when scheduled activities are due.',
      imageUrl: ['https://res.cloudinary.com/db3m7jneg/image/upload/v1739186607/Macbook-Air-exercise-tracker-arena.vercel.app_dg89u9.png'],
      liveUrl: 'https://exercise-tracker-arena.vercel.app/',
      githubUrl: 'https://github.com/Fredrickmureti/exercise-tracker',
      tags: ['React', 'CSS', 'JavaScript', 'Node.js', 'Express', 'MongoDB'],
      isPrivate: false,
    },
  ],
  funProjects: [
    {
      name: 'Meme Maestro',
      description: 'A professional-grade meme creation tool built with React and TypeScript. Create, customize, and share memes with an intuitive interface and powerful features.',
      imageUrl: ['https://res.cloudinary.com/db3m7jneg/image/upload/v1739829147/Macbook-Air-meme-maestro.vercel.app_veo7zu.png'],
      liveUrl: 'https://meme-maestro.vercel.app/',
      githubUrl: 'https://github.com/Fredrickmureti/meme_maestro',
      tags: ['JavaScript', 'React', 'Tailwind CSS', 'Typescript'],
      isPrivate: false,
    },
    {
      name: 'TicTacToe Game With Background Music',
      description: 'This project is a Tic-Tac-Toe game with a polished user interface, customizable player names, and background music. The music changes automatically as each track finishes and can be toggled on or off.',
      imageUrl: ['https://res.cloudinary.com/db3m7jneg/image/upload/v1739225174/Macbook-Air-tic-tac-toe-hazel-five.vercel.app_kftlgv.png'],
      liveUrl: 'https://tic-tac-toe-hazel-five.vercel.app/',
      githubUrl: 'https://github.com/Fredrickmureti/Tic-Tac-Toe',
      tags: ['JavaScript', 'HTML', 'CSS'],
      isPrivate: false,
    },
    {
      name: 'Candy Crush Game',
      description: 'A fun Candy Crush game implemented in HTML, CSS, and JavaScript, featuring colorful candies, scoring, and streak tracking. The game includes swipe functionality for mobile devices, music control, and more.',
      imageUrl: ['https://res.cloudinary.com/db3m7jneg/image/upload/v1739224514/Galaxy-Tab-S7-candy-crush-gilt.vercel.app_pnfxas.png'],
      liveUrl: 'https://candy-crush-gilt.vercel.app/',
      githubUrl: 'https://github.com/Fredrickmureti/CANDY_CRUSH',
      tags: ['JavaScript', 'HTML', 'CSS'],
      isPrivate: false,
    },
    {
      name: '25 + 5 Clock',
      description: 'This project is a Pomodoro-style clock built with React. The 25 + 5 clock features a 25-minute work session followed by a 5-minute break session. The clock counts down each session and automatically switches between work and break modes.',
      imageUrl: ['https://res.cloudinary.com/db3m7jneg/image/upload/v1739223122/Macbook-Air-javascript-clock-cyan.vercel.app_qed7tc.png'],
      liveUrl: 'https://javascript-clock-cyan.vercel.app/',
      githubUrl: 'https://github.com/Fredrickmureti/javascript_clock',
      tags: ['JavaScript', 'React', 'CSS'],
      isPrivate: false,
    },
    {
      name: 'Drum Machine',
      description: 'The Drum Machine is a simple web application that allows users to play different drum sounds using their keyboard or by clicking on buttons. The application features two sound banks and a control panel for power, volume, and sound bank toggling.',
      imageUrl: ['https://res.cloudinary.com/db3m7jneg/image/upload/v1739224302/Macbook-Air-drum-machine-two-pi.vercel.app_pooka3.png'],
      liveUrl: 'https://drum-machine-two-pi.vercel.app/',
      githubUrl: 'https://github.com/Fredrickmureti/Drum-Machine',
      tags: ['JavaScript', 'React', 'CSS'],
      isPrivate: false,
    },
    {
      name: '3D Character Creator',
      description: 'A powerful web-based 3D character creation tool that allows users to design and customize their own 3D characters with photo textures and various customization options.',
      imageUrl: ['https://res.cloudinary.com/db3m7jneg/image/upload/v1739235920/Macbook-Air-3-d-character-creator.vercel.app_coroub.png'],
      liveUrl: 'https://3-d-character-creator.vercel.app/',
      githubUrl: 'https://github.com/Fredrickmureti/3D_Character_Creator',
      tags: ['JavaScript', 'React', 'Tailwind CSS', 'Typescript', '3js'],
      isPrivate: false,
    },
  ]
};

export default personalProjects;
